/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz_game;

import java.awt.Color;

/**
 *
 * @author David
 */
public class Choices extends javax.swing.JFrame {

    /**
     * Creates new form Choices
     */
    public Choices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        Message1 = new javax.swing.JLabel();
        Quick = new javax.swing.JButton();
        Normal = new javax.swing.JButton();
        Advanced = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Menu.setBackground(new java.awt.Color(255, 242, 219));
        Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Menu.setFocusable(false);
        Menu.setPreferredSize(new java.awt.Dimension(815, 477));
        Menu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MenuMouseDragged(evt);
            }
        });
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuMousePressed(evt);
            }
        });

        Message1.setBackground(new java.awt.Color(0, 0, 0));
        Message1.setFont(new java.awt.Font("Permanent Marker", 0, 18)); // NOI18N
        Message1.setForeground(new java.awt.Color(0, 0, 0));
        Message1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Message1.setText("pick your difficulty:");
        Message1.setMaximumSize(new java.awt.Dimension(100, 19));
        Message1.setPreferredSize(new java.awt.Dimension(100, 19));

        Quick.setBackground(new java.awt.Color(153, 255, 153));
        Quick.setFont(new java.awt.Font("Permanent Marker", 0, 18)); // NOI18N
        Quick.setForeground(new java.awt.Color(0, 0, 0));
        Quick.setText("Quick");
        Quick.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Quick.setBorderPainted(false);
        Quick.setFocusPainted(false);
        Quick.setFocusable(false);
        Quick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QuickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QuickMouseExited(evt);
            }
        });
        Quick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuickActionPerformed(evt);
            }
        });

        Normal.setBackground(new java.awt.Color(255, 255, 153));
        Normal.setFont(new java.awt.Font("Permanent Marker", 0, 18)); // NOI18N
        Normal.setForeground(new java.awt.Color(0, 0, 0));
        Normal.setText("Normal");
        Normal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Normal.setBorderPainted(false);
        Normal.setFocusPainted(false);
        Normal.setFocusable(false);
        Normal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NormalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NormalMouseExited(evt);
            }
        });
        Normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NormalActionPerformed(evt);
            }
        });

        Advanced.setBackground(new java.awt.Color(255, 102, 102));
        Advanced.setFont(new java.awt.Font("Permanent Marker", 0, 18)); // NOI18N
        Advanced.setForeground(new java.awt.Color(0, 0, 0));
        Advanced.setText("advanced");
        Advanced.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Advanced.setBorderPainted(false);
        Advanced.setFocusPainted(false);
        Advanced.setFocusable(false);
        Advanced.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdvancedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdvancedMouseExited(evt);
            }
        });
        Advanced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdvancedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(Message1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Normal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quick, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Advanced, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Message1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Quick)
                .addGap(18, 18, 18)
                .addComponent(Normal)
                .addGap(18, 18, 18)
                .addComponent(Advanced)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    int lastX, lastY, lastLocationX, lastLocationY;
    
    private void QuickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuickMouseEntered
        // TODO add your handling code here:

        this.Quick.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_QuickMouseEntered

    private void QuickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuickMouseExited
        // TODO add your handling code here:

        this.Quick.setBackground(new Color(153,255,153));
    }//GEN-LAST:event_QuickMouseExited

    private void QuickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuickActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        Attributes.setNumQuestions(5);
        Attributes.setDifficulty("Quick");
        
        Operations operation = new Operations();
        operation.updateDifficulty("Quick");
        
        Grammar grammar = new Grammar();
        grammar.setVisible(true);
    }//GEN-LAST:event_QuickActionPerformed

    private void MenuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseDragged
        // TODO add your handling code here:

        //To drag the window
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        lastLocationX = getLocationOnScreen().x + x - lastX;
        lastLocationY = getLocationOnScreen().y + y - lastY;

        setLocation(getLocationOnScreen().x + x - lastX,
            getLocationOnScreen().y + y - lastY);
        lastX = x;
        lastY = y;
    }//GEN-LAST:event_MenuMouseDragged

    private void MenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMousePressed
        // TODO add your handling code here:

        //Get the last position of the window
        lastX = evt.getXOnScreen();
        lastY = evt.getYOnScreen();
    }//GEN-LAST:event_MenuMousePressed

    private void NormalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NormalMouseEntered
        // TODO add your handling code here:
        
        this.Normal.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_NormalMouseEntered

    private void NormalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NormalMouseExited
        // TODO add your handling code here:
        
        this.Normal.setBackground(new Color(255,255,153));
    }//GEN-LAST:event_NormalMouseExited

    private void NormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NormalActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        Attributes.setNumQuestions(15);
        Attributes.setDifficulty("Normal");
        
        Operations operation = new Operations();
        operation.updateDifficulty("Normal");
        
        Grammar grammar = new Grammar();
        grammar.setVisible(true);
        
    }//GEN-LAST:event_NormalActionPerformed

    private void AdvancedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdvancedMouseEntered
        // TODO add your handling code here:
        
        this.Advanced.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_AdvancedMouseEntered

    private void AdvancedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdvancedMouseExited
        // TODO add your handling code here:
        
        this.Advanced.setBackground(new Color(255,102,102));
    }//GEN-LAST:event_AdvancedMouseExited

    private void AdvancedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdvancedActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        Attributes.setNumQuestions(30);
        Attributes.setDifficulty("Advanced");
        
        Operations operation = new Operations();
        operation.updateDifficulty("Advanced");
        
        Grammar grammar = new Grammar();
        grammar.setVisible(true);
       
    }//GEN-LAST:event_AdvancedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Advanced;
    private javax.swing.JPanel Menu;
    public javax.swing.JLabel Message1;
    public javax.swing.JButton Normal;
    public javax.swing.JButton Quick;
    // End of variables declaration//GEN-END:variables
}
