/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz_game;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author David
 */
public class Main_menu extends javax.swing.JFrame {
   
    /**
     * Creates new form Main_menu
     */
    public Main_menu() {
        initComponents();
        
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        PlayButton = new javax.swing.JButton();
        OptionButton = new javax.swing.JButton();
        CareerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        Menu.setBackground(new java.awt.Color(255, 242, 219));
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Menu.setFocusable(false);
        Menu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MenuMouseDragged(evt);
            }
        });
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuMousePressed(evt);
            }
        });

        Title.setBackground(new java.awt.Color(0, 0, 0));
        Title.setFont(new java.awt.Font("Permanent Marker", 0, 48)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 0, 0));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("English quizlet");
        Title.setMaximumSize(new java.awt.Dimension(100, 19));
        Title.setPreferredSize(new java.awt.Dimension(100, 19));

        ExitButton.setBackground(new java.awt.Color(255, 255, 255));
        ExitButton.setFont(new java.awt.Font("Russo One", 1, 14)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 51, 51));
        ExitButton.setText("X");
        ExitButton.setFocusable(false);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        PlayButton.setBackground(new java.awt.Color(34, 151, 252));
        PlayButton.setFont(new java.awt.Font("Permanent Marker", 0, 18)); // NOI18N
        PlayButton.setForeground(new java.awt.Color(0, 0, 0));
        PlayButton.setText("PLAY");
        PlayButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PlayButton.setBorderPainted(false);
        PlayButton.setFocusPainted(false);
        PlayButton.setFocusable(false);
        PlayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PlayButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PlayButtonMouseExited(evt);
            }
        });
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });

        OptionButton.setBackground(new java.awt.Color(34, 151, 252));
        OptionButton.setFont(new java.awt.Font("Permanent Marker", 0, 18)); // NOI18N
        OptionButton.setForeground(new java.awt.Color(0, 0, 0));
        OptionButton.setText("Options");
        OptionButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OptionButton.setBorderPainted(false);
        OptionButton.setFocusPainted(false);
        OptionButton.setFocusable(false);
        OptionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OptionButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OptionButtonMouseExited(evt);
            }
        });
        OptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionButtonActionPerformed(evt);
            }
        });

        CareerButton.setBackground(new java.awt.Color(34, 151, 252));
        CareerButton.setFont(new java.awt.Font("Permanent Marker", 0, 18)); // NOI18N
        CareerButton.setForeground(new java.awt.Color(0, 0, 0));
        CareerButton.setText("career");
        CareerButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CareerButton.setBorderPainted(false);
        CareerButton.setFocusPainted(false);
        CareerButton.setFocusable(false);
        CareerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CareerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CareerButtonMouseExited(evt);
            }
        });
        CareerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CareerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitButton))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 209, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CareerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(347, 347, 347))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ExitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CareerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    int lastX, lastY, lastLocationX, lastLocationY;
    
    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        
        System.exit(0); //Close the app    
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void MenuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseDragged
        // TODO add your handling code here:
        
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        lastLocationX = getLocationOnScreen().x + x - lastX;
        lastLocationY = getLocationOnScreen().y + y - lastY;
                   
        setLocation(getLocationOnScreen().x + x - lastX,
                    getLocationOnScreen().y + y - lastY);
            lastX = x;
            lastY = y;
             
    }//GEN-LAST:event_MenuMouseDragged

    private void MenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMousePressed
        lastX = evt.getXOnScreen();
        lastY = evt.getYOnScreen();
    }//GEN-LAST:event_MenuMousePressed

    private void PlayButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayButtonMouseEntered
        // TODO add your handling code here:
       
        this.PlayButton.setBackground(new Color(102, 238, 107));
    }//GEN-LAST:event_PlayButtonMouseEntered

    private void PlayButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayButtonMouseExited
        // TODO add your handling code here:
        
        this.PlayButton.setBackground(new Color(34, 151, 252));
    }//GEN-LAST:event_PlayButtonMouseExited

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        // TODO add your handling code here:
        Message message = new Message();
        Play_Choice playChoice = new Play_Choice();
        Operations operation = new Operations();
        
        PlayButton.setEnabled(false);
        CareerButton.setEnabled(false);
        OptionButton.setEnabled(false);
             
        if (operation.checkIfThereIsUser() == true) {
            
            this.setVisible(false);
            playChoice.setLocation(this.getLocation());
            playChoice.setVisible(true);
        }
        else {
           
            message.setAlwaysOnTop(true);
            message.setVisible(true);
 
        }
        
        message.ExitButton.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent a){ 
                     PlayButton.setEnabled(true);
                     CareerButton.setEnabled(true);
                     OptionButton.setEnabled(true);
                    }   
                });
        
        message.ConfirmButton.addActionListener(new ActionListener(){;
                  public void actionPerformed(ActionEvent a){ 
                     proceedToPlayChoice();
                    }   
                });
    }//GEN-LAST:event_PlayButtonActionPerformed
    
    private void proceedToPlayChoice() {
        this.setVisible(false);
        Play_Choice playChoice = new Play_Choice();
        
        playChoice.setVisible(true);
    }
    
    private void OptionButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionButtonMouseEntered
        // TODO add your handling code here:
        
        this.OptionButton.setBackground(new Color(102, 238, 107));
    }//GEN-LAST:event_OptionButtonMouseEntered

    private void OptionButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionButtonMouseExited
        // TODO add your handling code here:
        
        this.OptionButton.setBackground(new Color(34, 151, 252));
    }//GEN-LAST:event_OptionButtonMouseExited

    private void OptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionButtonActionPerformed
        // TODO add your handling code here:
        
        Options options = new Options();
        
        
        this.setVisible(false);
        options.setLocation(this.getLocation());
        options.setVisible(true);
        
    }//GEN-LAST:event_OptionButtonActionPerformed

    private void CareerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CareerButtonMouseEntered
        // TODO add your handling code here:
       
        this.CareerButton.setBackground(new Color(102, 238, 107));
    }//GEN-LAST:event_CareerButtonMouseEntered

    private void CareerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CareerButtonMouseExited
        // TODO add your handling code here:
        this.CareerButton.setBackground(new Color(34, 151, 252));
    }//GEN-LAST:event_CareerButtonMouseExited

    private void CareerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CareerButtonActionPerformed
        // TODO add your handling code here:
        
        Career career = new Career();
        Operations operation = new Operations();
        Message message = new Message();
        
        //Check if there is existing user
        if (operation.checkIfThereIsUser() == true) {
            this.setVisible(false);
            career.setLocation(this.getLocation());
            career.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(null, "Create your username first, click play to create!", "Message", JOptionPane.WARNING_MESSAGE);  
        }
        
    }//GEN-LAST:event_CareerButtonActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        
        this.setAutoRequestFocus(true);
        this.setEnabled(true);
      
    }//GEN-LAST:event_formWindowGainedFocus
    
  
    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton CareerButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JPanel Menu;
    public javax.swing.JButton OptionButton;
    public javax.swing.JButton PlayButton;
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
