/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz_game;

import java.awt.Color;

/**
 *
 * @author David
 */
public class Message2 extends javax.swing.JFrame {

    /**
     * Creates new form Message2
     */
    public Message2() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        Message1 = new javax.swing.JLabel();
        Yes = new javax.swing.JButton();
        No = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Menu.setBackground(new java.awt.Color(255, 242, 219));
        Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Menu.setFocusable(false);
        Menu.setPreferredSize(new java.awt.Dimension(815, 477));
        Menu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MenuMouseDragged(evt);
            }
        });
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuMousePressed(evt);
            }
        });

        Message1.setBackground(new java.awt.Color(0, 0, 0));
        Message1.setFont(new java.awt.Font("Permanent Marker", 0, 18)); // NOI18N
        Message1.setForeground(new java.awt.Color(0, 0, 0));
        Message1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Message1.setText("is this your final answer?");
        Message1.setMaximumSize(new java.awt.Dimension(100, 19));
        Message1.setPreferredSize(new java.awt.Dimension(100, 19));

        Yes.setBackground(new java.awt.Color(153, 255, 153));
        Yes.setFont(new java.awt.Font("Permanent Marker", 0, 18)); // NOI18N
        Yes.setForeground(new java.awt.Color(0, 0, 0));
        Yes.setText("YES");
        Yes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Yes.setBorderPainted(false);
        Yes.setFocusPainted(false);
        Yes.setFocusable(false);
        Yes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                YesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                YesMouseExited(evt);
            }
        });
        Yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesActionPerformed(evt);
            }
        });

        No.setBackground(new java.awt.Color(255, 102, 102));
        No.setFont(new java.awt.Font("Permanent Marker", 0, 18)); // NOI18N
        No.setForeground(new java.awt.Color(0, 0, 0));
        No.setText("NO");
        No.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        No.setBorderPainted(false);
        No.setFocusPainted(false);
        No.setFocusable(false);
        No.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NoMouseExited(evt);
            }
        });
        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(Yes, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(No, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(Message1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Message1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Yes, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(No, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    int lastX, lastY, lastLocationX, lastLocationY;
    
    private void MenuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseDragged
        // TODO add your handling code here:

        //To drag the window
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        lastLocationX = getLocationOnScreen().x + x - lastX;
        lastLocationY = getLocationOnScreen().y + y - lastY;

        setLocation(getLocationOnScreen().x + x - lastX,
            getLocationOnScreen().y + y - lastY);
        lastX = x;
        lastY = y;
    }//GEN-LAST:event_MenuMouseDragged

    private void MenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMousePressed
        // TODO add your handling code here:

        //Get the last position of the window
        lastX = evt.getXOnScreen();
        lastY = evt.getYOnScreen();
    }//GEN-LAST:event_MenuMousePressed

    private void YesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YesMouseEntered
        // TODO add your handling code here:
        
       this.Yes.setBackground(new Color(255,255,153));
    }//GEN-LAST:event_YesMouseEntered

    private void YesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YesMouseExited
        // TODO add your handling code here:
        
       this.Yes.setBackground(new Color(153,255,153));
    }//GEN-LAST:event_YesMouseExited

    private void YesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YesActionPerformed

    private void NoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoMouseEntered
        // TODO add your handling code here:
        
       this.No.setBackground(new Color(255,255,153));
    }//GEN-LAST:event_NoMouseEntered

    private void NoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoMouseExited
        // TODO add your handling code here:
        
         this.No.setBackground(new Color(255,102,102));
    }//GEN-LAST:event_NoMouseExited

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Message2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Message2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Message2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Message2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Message2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    public javax.swing.JLabel Message1;
    public javax.swing.JButton No;
    public javax.swing.JButton Yes;
    // End of variables declaration//GEN-END:variables
}
