/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz_game;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author David
 */
public class Play_Choice extends javax.swing.JFrame {

    /**
     * Creates new form PlayChoice
     */
    public Play_Choice() {
        initComponents();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        Menu = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        Choice1 = new javax.swing.JButton();
        Choice4 = new javax.swing.JButton();
        GrammarChoice = new javax.swing.JButton();
        Choice3 = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Menu.setBackground(new java.awt.Color(255, 242, 219));
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Menu.setFocusable(false);
        Menu.setPreferredSize(new java.awt.Dimension(815, 477));
        Menu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MenuMouseDragged(evt);
            }
        });
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuMousePressed(evt);
            }
        });

        Title.setBackground(new java.awt.Color(0, 0, 0));
        Title.setFont(new java.awt.Font("Permanent Marker", 0, 48)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 0, 0));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("choice");
        Title.setMaximumSize(new java.awt.Dimension(100, 19));
        Title.setPreferredSize(new java.awt.Dimension(100, 19));

        ExitButton.setBackground(new java.awt.Color(255, 255, 255));
        ExitButton.setFont(new java.awt.Font("Russo One", 1, 14)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 51, 51));
        ExitButton.setText("X");
        ExitButton.setFocusable(false);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        Choice1.setBackground(new java.awt.Color(34, 151, 252));
        Choice1.setFont(new java.awt.Font("Permanent Marker", 0, 18)); // NOI18N
        Choice1.setForeground(new java.awt.Color(0, 0, 0));
        Choice1.setText("casual");
        Choice1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Choice1.setBorderPainted(false);
        Choice1.setFocusPainted(false);
        Choice1.setFocusable(false);
        Choice1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Choice1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Choice1MouseExited(evt);
            }
        });
        Choice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choice1ActionPerformed(evt);
            }
        });

        Choice4.setBackground(new java.awt.Color(34, 151, 252));
        Choice4.setFont(new java.awt.Font("Permanent Marker", 0, 18)); // NOI18N
        Choice4.setForeground(new java.awt.Color(0, 0, 0));
        Choice4.setText("t or f");
        Choice4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Choice4.setBorderPainted(false);
        Choice4.setFocusPainted(false);
        Choice4.setFocusable(false);
        Choice4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Choice4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Choice4MouseExited(evt);
            }
        });
        Choice4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choice4ActionPerformed(evt);
            }
        });

        GrammarChoice.setBackground(new java.awt.Color(34, 151, 252));
        GrammarChoice.setFont(new java.awt.Font("Permanent Marker", 0, 18)); // NOI18N
        GrammarChoice.setForeground(new java.awt.Color(0, 0, 0));
        GrammarChoice.setText("grammar");
        GrammarChoice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GrammarChoice.setBorderPainted(false);
        GrammarChoice.setFocusPainted(false);
        GrammarChoice.setFocusable(false);
        GrammarChoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GrammarChoiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GrammarChoiceMouseExited(evt);
            }
        });
        GrammarChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrammarChoiceActionPerformed(evt);
            }
        });

        Choice3.setBackground(new java.awt.Color(34, 151, 252));
        Choice3.setFont(new java.awt.Font("Permanent Marker", 0, 18)); // NOI18N
        Choice3.setForeground(new java.awt.Color(0, 0, 0));
        Choice3.setText("spelling");
        Choice3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Choice3.setBorderPainted(false);
        Choice3.setFocusPainted(false);
        Choice3.setFocusable(false);
        Choice3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Choice3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Choice3MouseExited(evt);
            }
        });
        Choice3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choice3ActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(255, 255, 255));
        BackButton.setFont(new java.awt.Font("Russo One", 1, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 51, 51));
        BackButton.setText("<");
        BackButton.setFocusable(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButton)
                .addContainerGap())
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(GrammarChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(Choice3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(Choice4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton)
                    .addComponent(BackButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GrammarChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Choice4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Choice3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     
     int lastX;
     int lastY;
     int lastLocationX;
     int lastLocationY;
    
    private void closeThisWindow(){
        this.setVisible(false);
    }
    
    
    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:

        System.exit(0); //Close the app
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void Choice1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Choice1MouseEntered
        // TODO add your handling code here:

        this.Choice1.setBackground(new Color(102, 238, 107));
    }//GEN-LAST:event_Choice1MouseEntered

    private void Choice1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Choice1MouseExited
        // TODO add your handling code here:

        this.Choice1.setBackground(new Color(34, 151, 252));

    }//GEN-LAST:event_Choice1MouseExited

    private void Choice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Choice1ActionPerformed

    private void Choice4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Choice4MouseEntered
        // TODO add your handling code here:

        this.Choice4.setBackground(new Color(102, 238, 107));
    }//GEN-LAST:event_Choice4MouseEntered

    private void Choice4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Choice4MouseExited
        // TODO add your handling code here:

        this.Choice4.setBackground(new Color(34, 151, 252));
    }//GEN-LAST:event_Choice4MouseExited

    private void Choice4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choice4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Choice4ActionPerformed

    private void GrammarChoiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrammarChoiceMouseEntered
        // TODO add your handling code here:

        this.GrammarChoice.setBackground(new Color(102, 238, 107));
    }//GEN-LAST:event_GrammarChoiceMouseEntered

    private void GrammarChoiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrammarChoiceMouseExited
        // TODO add your handling code here:

        this.GrammarChoice.setBackground(new Color(34, 151, 252));
    }//GEN-LAST:event_GrammarChoiceMouseExited

    private void GrammarChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrammarChoiceActionPerformed
        // TODO add your handling code here:
        Choices choices = new Choices();
        
        choices.setAlwaysOnTop(true);
        choices.setVisible(true);
      
        choices.Quick.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e) {
            closeThisWindow();
            }
        });
    
        choices.Normal.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent c) {
            closeThisWindow();
            }
        });
    
        choices.Advanced.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent d) {
            closeThisWindow();
            }
        });

    }//GEN-LAST:event_GrammarChoiceActionPerformed

    private void MenuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseDragged
        // TODO add your handling code here:

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        lastLocationX = getLocationOnScreen().x + x - lastX;
        lastLocationY = getLocationOnScreen().y + y - lastY;
                   
        setLocation(getLocationOnScreen().x + x - lastX,
                    getLocationOnScreen().y + y - lastY);
            lastX = x;
            lastY = y;

    }//GEN-LAST:event_MenuMouseDragged

    private void MenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMousePressed
        lastX = evt.getXOnScreen();
        lastY = evt.getYOnScreen();
    }//GEN-LAST:event_MenuMousePressed

    private void Choice3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Choice3MouseEntered
        // TODO add your handling code here:
        
         this.Choice3.setBackground(new Color(102, 238, 107));
    }//GEN-LAST:event_Choice3MouseEntered

    private void Choice3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Choice3MouseExited
        // TODO add your handling code here:
        
        this.Choice3.setBackground(new Color(34, 151, 252));
    }//GEN-LAST:event_Choice3MouseExited

    private void Choice3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choice3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Choice3ActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        Main_menu mainMenu = new Main_menu(); 
        
        this.setVisible(false);
        mainMenu.setLocation(this.getLocation());
        mainMenu.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play_Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play_Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play_Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play_Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Play_Choice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton Choice1;
    private javax.swing.JButton Choice3;
    private javax.swing.JButton Choice4;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton GrammarChoice;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel Title;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
